# Generated by Django 2.0.7 on 2020-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
